###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
#            n0k0m3 | https://github.com/n0k0m3               #
###############################################################

name: Build ReTwitter

on:
  workflow_dispatch:
  push:
    paths:
      - 'retwitter/dl_twitter-version.json'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download Twitter
      run: |
        cd retwitter
        chmod +x dl_twitter.sh
        ./dl_twitter.sh

    - name: Compile ReTwitter
      run: |
        cd retwitter
        chmod +x compile_retwitter.sh
        ./compile_retwitter.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign package(s)
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: retwitter/output
        alias: ${{ secrets.ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"

    - name: Upload package(s)
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "ReTwitter r${{ env.date_now }}"
        files: |
          retwitter/output/retwitter-signed.apk
